export enum CollectionStatus {
  COLLECTION_STATUS_UNSPECIFIED = 'COLLECTION_STATUS_UNSPECIFIED',
  COLLECTION_STATUS_CREATED = 'COLLECTION_STATUS_CREATED',
  COLLECTION_STATUS_LOADING_COLLECTION = 'COLLECTION_STATUS_LOADING_COLLECTION',
  COLLECTION_STATUS_COLLECTION_LOADED = 'COLLECTION_STATUS_COLLECTION_LOADED',
  COLLECTION_STATUS_LOADING_NFTS = 'COLLECTION_STATUS_LOADING_NFTS',
  COLLECTION_STATUS_NFTS_LOADED = 'COLLECTION_STATUS_NFTS_LOADED',
  COLLECTION_STATUS_READY = 'COLLECTION_STATUS_READY',
}
