export enum NftStatus {
  NFT_STATUS_UNSPECIFIED = 'NFT_STATUS_UNSPECIFIED',
  NFT_STATUS_LISTING = 'NFT_STATUS_LISTING',
  NFT_STATUS_SALE = 'NFT_STATUS_SALE',
  NFT_STATUS_CANCEL_LISTING = 'NFT_STATUS_CANCEL_LISTING',
}
